spring:
  application:
    name: inspection-bmi
  datasource:
    url: jdbc:mysql://localhost:3306/inspection_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create | create-drop | update | validate | none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Logging SQL (optional, để debug)
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
