spring:
  application:
    name: inspection-bmi
  datasource:
    url: jdbc:mysql://localhost:3306/inspection_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # create | create-drop | update | validate | none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# Template and temp path configuration
app:
  template.path: classpath:templates/
  temp.path: /tmp/
  libreoffice.path: /Applications/LibreOffice.app/Contents/MacOS/soffice
  document:
    generation:
      strategy: docx-only # Options: docx-only, simple, improved, template-engine, auto
  export:
    dir: uploads/exports
    url: /api/exports/**

  # Logging SQL (optional, để debug)
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

custom:
  data:
    user:
      fullName: Admin
      username: admin
      password: $2a$10$zkKynXsI4WzSDCjoD0jcs.IKLtIBoMnwKz6pBUYBFa2PDFjhbxuve
      email: admin@gmail.com
      role: ADMIN
      phone: 0123456789
      dob: 2000-01-01
      note: Test user for login
